- name: Check installation via apt
  set_fact:
    install_apt: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 17

- name: Install the zstandard package in Debian derivatives
  apt:
    name: zstd
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: install_apt

- block:
    - tempfile: state=directory
      register: temp_dir

    - unarchive:
        src: https://github.com/facebook/zstd/archive/v{{ zstandard_version }}.tar.gz
        remote_src: yes
        dest: "{{ temp_dir.path }}"

    - make:
        chdir: "{{ temp_dir.path }}/zstd-{{ zstandard_version }}"
        target: install

  always:
    - file: path="{{ temp_dir.path }}" state=absent
  when: not install_apt
